[features]
seeds = false
skip-lint = false

[programs.localnet]
veil_program = "3qhVPvz8T1WiozCLEfhUuv8WZHDPpEfnAzq2iSatULc7"

[programs.devnet]
veil_program = "3qhVPvz8T1WiozCLEfhUuv8WZHDPpEfnAzq2iSatULc7"

[programs.mainnet]
veil_program = "3qhVPvz8T1WiozCLEfhUuv8WZHDPpEfnAzq2iSatULc7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["crates/program"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
